// Generated by gencpp from file rosplan_knowledge_msgs/GenerateProblemService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GENERATEPROBLEMSERVICE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GENERATEPROBLEMSERVICE_H

#include <ros/service_traits.h>


#include <rosplan_knowledge_msgs/GenerateProblemServiceRequest.h>
#include <rosplan_knowledge_msgs/GenerateProblemServiceResponse.h>


namespace rosplan_knowledge_msgs
{

struct GenerateProblemService
{

typedef GenerateProblemServiceRequest Request;
typedef GenerateProblemServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateProblemService
} // namespace rosplan_knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemService > {
  static const char* value()
  {
    return "691992df67730037ceca53e2831f2e82";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemService&) { return value(); }
};

template<>
struct DataType< ::rosplan_knowledge_msgs::GenerateProblemService > {
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GenerateProblemService";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemServiceRequest> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GenerateProblemServiceRequest> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GenerateProblemService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GenerateProblemServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GenerateProblemService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemServiceResponse> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GenerateProblemService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GenerateProblemServiceResponse> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GenerateProblemService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GenerateProblemServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GenerateProblemService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GenerateProblemServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GENERATEPROBLEMSERVICE_H
