// Generated by gencpp from file rosplan_knowledge_msgs/GetDomainNameService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICE_H

#include <ros/service_traits.h>


#include <rosplan_knowledge_msgs/GetDomainNameServiceRequest.h>
#include <rosplan_knowledge_msgs/GetDomainNameServiceResponse.h>


namespace rosplan_knowledge_msgs
{

struct GetDomainNameService
{

typedef GetDomainNameServiceRequest Request;
typedef GetDomainNameServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDomainNameService
} // namespace rosplan_knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameService > {
  static const char* value()
  {
    return "60174b39a7780212f0384c8d050df5a0";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameService&) { return value(); }
};

template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainNameService > {
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetDomainNameService";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameServiceRequest> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainNameServiceRequest> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainNameService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainNameServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetDomainNameService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainNameService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetDomainNameService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICE_H
