// Generated by gencpp from file rosplan_knowledge_msgs/GetDomainOperatorDetailsService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINOPERATORDETAILSSERVICE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINOPERATORDETAILSSERVICE_H

#include <ros/service_traits.h>


#include <rosplan_knowledge_msgs/GetDomainOperatorDetailsServiceRequest.h>
#include <rosplan_knowledge_msgs/GetDomainOperatorDetailsServiceResponse.h>


namespace rosplan_knowledge_msgs
{

struct GetDomainOperatorDetailsService
{

typedef GetDomainOperatorDetailsServiceRequest Request;
typedef GetDomainOperatorDetailsServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDomainOperatorDetailsService
} // namespace rosplan_knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > {
  static const char* value()
  {
    return "e9c0dee3aa886db3ed46d5fff1adf3ae";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService&) { return value(); }
};

template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > {
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetDomainOperatorDetailsService";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService > 
template<>
struct DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::GetDomainOperatorDetailsService >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::GetDomainOperatorDetailsServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINOPERATORDETAILSSERVICE_H
