// Generated by gencpp from file rosplan_knowledge_msgs/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_REMOVEWAYPOINT_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <rosplan_knowledge_msgs/RemoveWaypointRequest.h>
#include <rosplan_knowledge_msgs/RemoveWaypointResponse.h>


namespace rosplan_knowledge_msgs
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace rosplan_knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::rosplan_knowledge_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "rosplan_knowledge_msgs/RemoveWaypoint";
  }

  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypointRequest> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypoint > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::RemoveWaypointRequest> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::RemoveWaypoint > 
template<>
struct DataType< ::rosplan_knowledge_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypointResponse> should match 
// service_traits::MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypoint > 
template<>
struct MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_knowledge_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_knowledge_msgs::RemoveWaypointResponse> should match 
// service_traits::DataType< ::rosplan_knowledge_msgs::RemoveWaypoint > 
template<>
struct DataType< ::rosplan_knowledge_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_knowledge_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rosplan_knowledge_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_REMOVEWAYPOINT_H
