// Generated by gencpp from file rosplan_dispatch_msgs/ActionDispatch.msg
// DO NOT EDIT!


#ifndef ROSPLAN_DISPATCH_MSGS_MESSAGE_ACTIONDISPATCH_H
#define ROSPLAN_DISPATCH_MSGS_MESSAGE_ACTIONDISPATCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <diagnostic_msgs/KeyValue.h>

namespace rosplan_dispatch_msgs
{
template <class ContainerAllocator>
struct ActionDispatch_
{
  typedef ActionDispatch_<ContainerAllocator> Type;

  ActionDispatch_()
    : action_id(0)
    , name()
    , parameters()
    , duration(0.0)
    , dispatch_time(0.0)  {
    }
  ActionDispatch_(const ContainerAllocator& _alloc)
    : action_id(0)
    , name(_alloc)
    , parameters(_alloc)
    , duration(0.0)
    , dispatch_time(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _action_id_type;
  _action_id_type action_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector< ::diagnostic_msgs::KeyValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::other >  _parameters_type;
  _parameters_type parameters;

   typedef float _duration_type;
  _duration_type duration;

   typedef float _dispatch_time_type;
  _dispatch_time_type dispatch_time;





  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> const> ConstPtr;

}; // struct ActionDispatch_

typedef ::rosplan_dispatch_msgs::ActionDispatch_<std::allocator<void> > ActionDispatch;

typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ActionDispatch > ActionDispatchPtr;
typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ActionDispatch const> ActionDispatchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosplan_dispatch_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosplan_dispatch_msgs': ['/home/ys/MOMDP_DESPOT/ROSPlan/src/rosplan/rosplan_dispatch_msgs/msg', '/home/ys/MOMDP_DESPOT/ROSPlan/devel/share/rosplan_dispatch_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80f1ebdf8c68451c7e598f98e7f12dba";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80f1ebdf8c68451cULL;
  static const uint64_t static_value2 = 0x7e598f98e7f12dbaULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_dispatch_msgs/ActionDispatch";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#actionDispatch message\n\
int32 action_id\n\
string name\n\
diagnostic_msgs/KeyValue[] parameters\n\
float32 duration\n\
float32 dispatch_time\n\
\n\
================================================================================\n\
MSG: diagnostic_msgs/KeyValue\n\
string key # what to label this value when viewing\n\
string value # a value to track over time\n\
";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_id);
      stream.next(m.name);
      stream.next(m.parameters);
      stream.next(m.duration);
      stream.next(m.dispatch_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionDispatch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_dispatch_msgs::ActionDispatch_<ContainerAllocator>& v)
  {
    s << indent << "action_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action_id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
    s << indent << "dispatch_time: ";
    Printer<float>::stream(s, indent + "  ", v.dispatch_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_DISPATCH_MSGS_MESSAGE_ACTIONDISPATCH_H
