// Generated by gencpp from file rosplan_dispatch_msgs/PlanningService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICE_H
#define ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICE_H

#include <ros/service_traits.h>


#include <rosplan_dispatch_msgs/PlanningServiceRequest.h>
#include <rosplan_dispatch_msgs/PlanningServiceResponse.h>


namespace rosplan_dispatch_msgs
{

struct PlanningService
{

typedef PlanningServiceRequest Request;
typedef PlanningServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanningService
} // namespace rosplan_dispatch_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_dispatch_msgs::PlanningService > {
  static const char* value()
  {
    return "b620a1e7a07d465aa5a10fe0ee615756";
  }

  static const char* value(const ::rosplan_dispatch_msgs::PlanningService&) { return value(); }
};

template<>
struct DataType< ::rosplan_dispatch_msgs::PlanningService > {
  static const char* value()
  {
    return "rosplan_dispatch_msgs/PlanningService";
  }

  static const char* value(const ::rosplan_dispatch_msgs::PlanningService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_dispatch_msgs::PlanningServiceRequest> should match 
// service_traits::MD5Sum< ::rosplan_dispatch_msgs::PlanningService > 
template<>
struct MD5Sum< ::rosplan_dispatch_msgs::PlanningServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_dispatch_msgs::PlanningService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_dispatch_msgs::PlanningServiceRequest> should match 
// service_traits::DataType< ::rosplan_dispatch_msgs::PlanningService > 
template<>
struct DataType< ::rosplan_dispatch_msgs::PlanningServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_dispatch_msgs::PlanningService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_dispatch_msgs::PlanningServiceResponse> should match 
// service_traits::MD5Sum< ::rosplan_dispatch_msgs::PlanningService > 
template<>
struct MD5Sum< ::rosplan_dispatch_msgs::PlanningServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_dispatch_msgs::PlanningService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_dispatch_msgs::PlanningServiceResponse> should match 
// service_traits::DataType< ::rosplan_dispatch_msgs::PlanningService > 
template<>
struct DataType< ::rosplan_dispatch_msgs::PlanningServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_dispatch_msgs::PlanningService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICE_H
