// Generated by gencpp from file rosplan_dispatch_msgs/ProblemService.msg
// DO NOT EDIT!


#ifndef ROSPLAN_DISPATCH_MSGS_MESSAGE_PROBLEMSERVICE_H
#define ROSPLAN_DISPATCH_MSGS_MESSAGE_PROBLEMSERVICE_H

#include <ros/service_traits.h>


#include <rosplan_dispatch_msgs/ProblemServiceRequest.h>
#include <rosplan_dispatch_msgs/ProblemServiceResponse.h>


namespace rosplan_dispatch_msgs
{

struct ProblemService
{

typedef ProblemServiceRequest Request;
typedef ProblemServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProblemService
} // namespace rosplan_dispatch_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosplan_dispatch_msgs::ProblemService > {
  static const char* value()
  {
    return "61fb3e0dd88c35b2c75cf0b688f40ee8";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ProblemService&) { return value(); }
};

template<>
struct DataType< ::rosplan_dispatch_msgs::ProblemService > {
  static const char* value()
  {
    return "rosplan_dispatch_msgs/ProblemService";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ProblemService&) { return value(); }
};


// service_traits::MD5Sum< ::rosplan_dispatch_msgs::ProblemServiceRequest> should match 
// service_traits::MD5Sum< ::rosplan_dispatch_msgs::ProblemService > 
template<>
struct MD5Sum< ::rosplan_dispatch_msgs::ProblemServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_dispatch_msgs::ProblemService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::ProblemServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_dispatch_msgs::ProblemServiceRequest> should match 
// service_traits::DataType< ::rosplan_dispatch_msgs::ProblemService > 
template<>
struct DataType< ::rosplan_dispatch_msgs::ProblemServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rosplan_dispatch_msgs::ProblemService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::ProblemServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosplan_dispatch_msgs::ProblemServiceResponse> should match 
// service_traits::MD5Sum< ::rosplan_dispatch_msgs::ProblemService > 
template<>
struct MD5Sum< ::rosplan_dispatch_msgs::ProblemServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosplan_dispatch_msgs::ProblemService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::ProblemServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosplan_dispatch_msgs::ProblemServiceResponse> should match 
// service_traits::DataType< ::rosplan_dispatch_msgs::ProblemService > 
template<>
struct DataType< ::rosplan_dispatch_msgs::ProblemServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rosplan_dispatch_msgs::ProblemService >::value();
  }
  static const char* value(const ::rosplan_dispatch_msgs::ProblemServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPLAN_DISPATCH_MSGS_MESSAGE_PROBLEMSERVICE_H
